import { useSchedulerStore } from '../../store/useSchedulerStore';

export function PrintView() {
  const { sessions, eventConfig, selectedDay } = useSchedulerStore();

  const formatTime = (time: string) => {
    const [hours, mins] = time.split(':').map(Number);
    const period = hours >= 12 ? 'PM' : 'AM';
    const displayHours = hours % 12 || 12;
    return `${displayHours}:${String(mins).padStart(2, '0')} ${period}`;
  };

  return (
    <div className="hidden print:block p-8">
      <h1 className="text-2xl font-bold mb-2">{eventConfig.name}</h1>
      <h2 className="text-xl mb-6">{selectedDay}</h2>

      <table className="w-full border-collapse">
        <thead>
          <tr>
            <th className="border border-gray-400 p-2 bg-gray-100">Time</th>
            {eventConfig.rooms.map((room) => (
              <th key={room.id} className="border border-gray-400 p-2 bg-gray-100">
                {room.name}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {eventConfig.timeSlots.map((slot) => (
            <tr key={slot.id}>
              <td className="border border-gray-400 p-2 font-medium">
                {formatTime(slot.startTime)} - {formatTime(slot.endTime)}
              </td>
              {eventConfig.rooms.map((room) => {
                const session = sessions.find(
                  (s) =>
                    s.day === selectedDay &&
                    s.timeSlot === slot.startTime &&
                    s.roomId === room.id
                );

                return (
                  <td key={room.id} className="border border-gray-400 p-2">
                    {session ? (
                      <div>
                        <div className="font-medium">{session.sessionTitle}</div>
                        <div className="text-sm text-gray-600">{session.presenterName}</div>
                      </div>
                    ) : (
                      <span className="text-gray-400">-</span>
                    )}
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
      </table>

      <div className="mt-8 text-sm text-gray-500">
        Generated by Conference Scheduler 2026
      </div>
    </div>
  );
}
